name: pika_patrol
description: "Patrol, track, and log pikas"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.1.0+210

environment:
  sdk: '>=3.3.0-71.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.20.0
  firebase_core_web: ^2.8.1
  firebase_auth: ^4.12.0
  firebase_auth_web: ^5.8.5
  firebase_storage: ^11.4.0
  cloud_firestore: ^4.12.1
  cloud_firestore_web: ^3.8.2

  google_sign_in: ^6.1.5
  flutter_localizations:
    sdk: flutter
    version: ^0.0.0
  intl: ^0.18.1
  flutter_plugin_android_lifecycle: ^2.0.17
  cupertino_icons: ^1.0.6
  provider: ^6.0.5
  image_cropper: ^5.0.0
  image_picker: ^1.0.4
  file_picker: ^6.0.0
  shimmer: ^3.0.0
  liquid_swipe: ^3.1.0
  curved_navigation_bar: ^1.0.3
  #  flutter_audio_recorder: ^0.5.5 TODO - fork flutter_audio_recorder for dart 3 compat, though I think the following does that already:
  flutter_audio_recorder3: ^0.0.5 #requires sdk >= 3.0.0 <4.0.0
  material_themes_widgets: ^1.12.0
  url_launcher: ^6.1.12 #requires sdk >= 3.0.0 <4.0.0
  chips_choice: ^3.0.0
  charcode: ^1.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  mime: ^1.0.4
  geolocator: ^9.0.2
  data_connection_checker_nulls: ^0.0.2
  shared_preferences: ^2.2.0
  permission_handler: ^11.0.1
  dash_flags: ^0.1.1
  language_code_icons: ^0.1.0
  gsheets: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.0
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter:

  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/audio/

  fonts:
    - family: LanguageCodes
      fonts:
        - asset: "packages/language_code_icons/assets/fonts/LanguageCodes.ttf"

flutter_icons:
  android: true
  image_path_android: "assets/icons/icon.png"
  ios: true
  image_path_ios: "assets/icons/icon_no_transparency.png"