// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8PRLrNZxWXr7SjmNTKM8sIFldEl-arlE',
    appId: '1:954700599379:android:4a351094efe317d98c36a6',
    messagingSenderId: '954700599379',
    projectId: 'pikajoe-97c5c',
    databaseURL: 'https://pikajoe-97c5c.firebaseio.com',
    storageBucket: 'pikajoe-97c5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOT98d6WYldKY0UPvt03TGzh5xQaccr1k',
    appId: '1:954700599379:ios:779983c3ccc366828c36a6',
    messagingSenderId: '954700599379',
    projectId: 'pikajoe-97c5c',
    databaseURL: 'https://pikajoe-97c5c.firebaseio.com',
    storageBucket: 'pikajoe-97c5c.appspot.com',
    androidClientId: '954700599379-60sbdv04n37o4rjug5hii117cc650sf7.apps.googleusercontent.com',
    iosClientId: '954700599379-qp2i96hjt2shcf3hmkoa8dvrb3nvpmp7.apps.googleusercontent.com',
    iosBundleId: 'com.tcubedstudios.pikaPatrol',
  );
}
